name: Draft

on:
  workflow_dispatch:
  push:
    # trigger only on main branch
    branches:
      - main
    # trigger only on changes to the following files
    paths:
      - "kilroy_face_twitter/src/**"
      - "kilroy_face_twitter/LICENSE"
      - "kilroy_face_twitter/README.md"
      - "kilroy_face_twitter/poetry.lock"
      - "kilroy_face_twitter/pyproject.toml"
      - ".github/workflows/draft.yml"
      - ".github/release-drafter.yml"

jobs:
  draft:
    name: Update draft release
    # better to use pinned version here
    runs-on: ubuntu-20.04
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
